---
- name: Setup server
  hosts: servers
  user: root

  roles:
#    - bootstrap
    - apelon-dts
    - mysql

- name: Configure server
  hosts: servers
  user: root

  roles:
    - mysql-config
    - ts-web
    - demo-data
