---  
- name: Set Mysql root password
  mysql_user: check_implicit_admin=yes login_user=root login_password={{ mysqlrootpwd }} name=root password={{ mysqlrootpwd }} state=present
  ignore_errors: True # Temp fix - ansible 1.3.4

- name: Create dts database
  mysql_db: name=dts state=present login_user=root login_password={{ mysqlrootpwd }} 

- name: Create dts mysql user
  mysql_user: name=dts state=present password={{ dtsmysqlpwd }} login_user=root login_password={{ mysqlrootpwd }} priv=dts.*:ALL
  notify: restart mysql

- name: Copy mysql credentials file 
  template: src=target-connection.xml dest=/opt/apelon-dts/bin/kb/target-connection.xml mode=0600

- name: Insert apelonserverprops.xml
  template: src=apelonserverprops.xml dest=/opt/apelon-dts/bin/server mode=0600

- name: Make scripts executable
  file: path=/opt/apelon-dts/bin/kb/create/kbcreate.sh mode=775

- name: change kbcreate to overwrite database (be careful)
  lineinfile: dest=/opt/apelon-dts/bin/kb/create/kbcreate.sh regexp=^exec line="exec java $JAVA_OPTIONS com.apelon.common.util.db.DbCreate -startSeq 2000000000000 -c com.apelon.dts.db.admin.config.DBCreateConfig -p kb/create/kbcreate.xml -t kb/target-connection.xml -skipPause" state=present

- name: Create dts schema
  shell: chdir=/opt/apelon-dts/bin/kb/create/ ./kbcreate.sh


